### ISSUE TITLE
Deprecated sync export used

### ISSUE THREAD

**Issue by Halama** [keboola/app-luckyguess#13]
![image](https://user-images.githubusercontent.com/903531/30539209-a9b42f76-9c71-11e7-90cf-21636f52e6fe.png)

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/30539274-ef9912ea-9c71-11e7-8342-edc5e9f5e322.png)

**Comment by Halama** [comment]
možná se to týká spíš tohodle repa? https://github.com/keboola/docker-lgr-bundle

**Comment by Halama** [comment]
https://github.com/keboola/connection/issues/911#issuecomment-330190577

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/30539716-0f8a1cdc-9c74-11e7-99cb-3675214ee9e5.png)

**Comment by Halama** [comment]
Podle verze sapi klienta to bude tedy nejspíš https://github.com/keboola/luckyguess-bundle/blob/58499664856c47ac69d44cfc501993637645e231/composer.lock#L1677

**Comment by Halama** [comment]
Hurá povedlo se mi to nasimulovat dělá to výpis spuštění receptu. Zkusím to fixnout:
![image](https://user-images.githubusercontent.com/903531/30540425-7120b1ec-9c77-11e7-99f7-8a566bdd70f0.png)

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/luckyguess-bundle/commit/915f8fb598297f159fadb803f3a96868d7071841
